### ISSUE TITLE
Installation problem with Node Js (v20.5.1) on Windows 11 (22H2)

### ISSUE THREAD

**Issue by leandjb** [nut-tree/TemplateMatcher#17]
When run the node command: 
```
npm i @nut-tree/template-matcher 
```
**It is not possible install the package** and appear the following **ERROR**: 
```
npm ERR! code 1
npm ERR! path Z:\rpa\rpa-image-loader\node_modules\opencv4nodejs-prebuilt
npm ERR! command failed
npm ERR! command C:\WINDOWS\system32\cmd.exe /d /s /c prebuild-install || (node ./install/dependencies.js && node ./install/install.js)
npm ERR! Installing prebuilt OpenCV vundefined for plattform win32
npm ERR! prebuild-install WARN install No prebuilt binaries found (target=20.5.1 runtime=node arch=x64 libc= platform=win32)
npm ERR! npm ERR! code ETARGET
npm ERR! npm ERR! notarget No matching version found for @nut-tree/opencv-build-win32@undefined.
npm ERR! npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! npm ERR! notarget a package version that doesn't exist.
npm ERR! 
npm ERR! npm ERR! A complete log of this run can be found in: C:\Users\AppData\Local\npm-cache\_logs\2023-08-17T01_27_24_367Z-debug-0.log
npm ERR! node:child_process:962
npm ERR!     throw err;
npm ERR!     ^
npm ERR!
npm ERR! Error: Command failed: npm install --no-save @nut-tree/opencv-build-win32@undefined
npm ERR! npm ERR! code ETARGET
npm ERR! npm ERR! notarget No matching version found for @nut-tree/opencv-build-win32@undefined.
npm ERR! npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! npm ERR! notarget a package version that doesn't exist.
npm ERR!
npm ERR! npm ERR! A complete log of this run can be found in: C:\Users\AppData\Local\npm-cache\_logs\2023-08-17T01_27_24_367Z-debug-0.log
npm ERR!
npm ERR!     at checkExecSyncError (node:child_process:887:11)
npm ERR!     at execSync (node:child_process:959:15)
npm ERR!     at install (Z:\rpa\rpa-image-loader\node_modules\opencv4nodejs-prebuilt\install\dependencies.js:5:5)
npm ERR!     at Object.<anonymous> (Z:\rpa\rpa-image-loader\node_modules\opencv4nodejs-prebuilt\install\dependencies.js:26:5)
npm ERR!     at Module._compile (node:internal/modules/cjs/loader:1233:14)
npm ERR!     at Module._extensions..js (node:internal/modules/cjs/loader:1287:10)
npm ERR!     at Module.load (node:internal/modules/cjs/loader:1091:32)
npm ERR!     at Module._load (node:internal/modules/cjs/loader:938:12)
npm ERR!     at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:83:12) {
npm ERR!   status: 1,
npm ERR!   signal: null,
npm ERR!   output: [
npm ERR!     null,
npm ERR!     Buffer(0) [Uint8Array] [],
npm ERR!     Buffer(381) [Uint8Array] [
npm ERR!       110, 112, 109,  32,  69,  82,  82,  33,  32,  99, 111, 100,
npm ERR!       101,  32,  69,  84,  65,  82,  71,  69,  84,  10, 110, 112,
npm ERR!       109,  32,  69,  82,  82,  33,  32, 110, 111, 116,  97, 114,
npm ERR!       103, 101, 116,  32,  78, 111,  32, 109,  97, 116,  99, 104,
npm ERR!       105, 110, 103,  32, 118, 101, 114, 115, 105, 111, 110,  32,
npm ERR!       102, 111, 117, 110, 100,  32, 102, 111, 114,  32,  64, 110,
npm ERR!       117, 116,  45, 116, 114, 101, 101,  47, 111, 112, 101, 110,
npm ERR!        99, 118,  45,  98, 117, 105, 108, 100,  45, 119, 105, 110,
npm ERR!        51,  50,  64, 117,
npm ERR!       ... 281 more items
npm ERR!     ]
npm ERR!   ],
npm ERR!   pid: 10684,
npm ERR!   stdout: Buffer(0) [Uint8Array] [],
npm ERR!   stderr: Buffer(381) [Uint8Array] [
npm ERR!     110, 112, 109,  32,  69,  82,  82,  33,  32,  99, 111, 100,
npm ERR!     101,  32,  69,  84,  65,  82,  71,  69,  84,  10, 110, 112,
npm ERR!     109,  32,  69,  82,  82,  33,  32, 110, 111, 116,  97, 114,
npm ERR!     103, 101, 116,  32,  78, 111,  32, 109,  97, 116,  99, 104,
npm ERR!     105, 110, 103,  32, 118, 101, 114, 115, 105, 111, 110,  32,
npm ERR!     102, 111, 117, 110, 100,  32, 102, 111, 114,  32,  64, 110,
npm ERR!     117, 116,  45, 116, 114, 101, 101,  47, 111, 112, 101, 110,
npm ERR!      99, 118,  45,  98, 117, 105, 108, 100,  45, 119, 105, 110,
npm ERR!      51,  50,  64, 117,
npm ERR!     ... 281 more items
npm ERR!   ]
npm ERR! }
npm ERR!
npm ERR! Node.js v20.5.1
```
---

PS: Finally i attached the node_log content:
*npm-cache\_logs\2023-08-17T01_27_24_367Z-debug-0.log*
```
0 verbose cli C:\Program Files\nodejs\node.exe C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js
1 info using npm@9.8.0
2 info using node@v20.5.1
3 timing npm:load:whichnode Completed in 3ms
4 timing config:load:defaults Completed in 2ms
5 timing config:load:file:C:\Program Files\nodejs\node_modules\npm\npmrc Completed in 3ms
6 timing config:load:builtin Completed in 3ms
7 timing config:load:cli Completed in 2ms
8 timing config:load:env Completed in 1ms
9 timing config:load:file:Z:\rpa\rpa-image-loader\node_modules\opencv4nodejs-prebuilt\.npmrc Completed in 1ms
10 timing config:load:project Completed in 2ms
11 timing config:load:file:C:\Users\.npmrc Completed in 0ms
12 timing config:load:user Completed in 0ms
13 timing config:load:file:C:\Users\AppData\Roaming\npm\etc\npmrc Completed in 0ms
14 timing config:load:global Completed in 0ms
15 timing config:load:setEnvs Completed in 1ms
16 timing config:load Completed in 11ms
17 timing npm:load:configload Completed in 11ms
18 timing config:load:flatten Completed in 1ms
19 timing npm:load:mkdirpcache Completed in 1ms
20 timing npm:load:mkdirplogs Completed in 0ms
21 verbose title npm install @nut-tree/opencv-build-win32@undefined
22 verbose argv "install" "--no-save" "@nut-tree/opencv-build-win32@undefined"
23 timing npm:load:setTitle Completed in 1ms
24 timing npm:load:display Completed in 1ms
25 verbose logfile logs-max:10 dir:C:\Users\AppData\Local\npm-cache\_logs\2023-08-17T01_27_24_367Z-
26 verbose logfile C:\Users\AppData\Local\npm-cache\_logs\2023-08-17T01_27_24_367Z-debug-0.log
27 timing npm:load:logFile Completed in 12ms
28 timing npm:load:timers Completed in 0ms
29 timing npm:load:configScope Completed in 0ms
30 timing npm:load Completed in 49ms
31 timing arborist:ctor Completed in 1ms
32 timing arborist:ctor Completed in 1ms
33 silly logfile start cleaning logs, removing 2 files
34 timing idealTree:init Completed in 15ms
35 silly logfile done cleaning log files
36 http fetch GET 200 https://registry.npmjs.org/@nut-tree%2fopencv-build-win32 15ms (cache hit)
37 timing idealTree Completed in 37ms
38 timing command:install Completed in 45ms
39 verbose type tag
40 verbose stack @nut-tree/opencv-build-win32: No matching version found for @nut-tree/opencv-build-win32@undefined.
40 verbose stack     at module.exports (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-pick-manifest\lib\index.js:209:23)
40 verbose stack     at RegistryFetcher.manifest (C:\Program Files\nodejs\node_modules\npm\node_modules\pacote\lib\registry.js:119:22)
40 verbose stack     at async C:\Program Files\nodejs\node_modules\npm\node_modules\@npmcli\arborist\lib\arborist\build-ideal-tree.js:527:22
40 verbose stack     at async Promise.all (index 0)
40 verbose stack     at async #add (C:\Program Files\nodejs\node_modules\npm\node_modules\@npmcli\arborist\lib\arborist\build-ideal-tree.js:516:5)
40 verbose stack     at async #applyUserRequestsToNode (C:\Program Files\nodejs\node_modules\npm\node_modules\@npmcli\arborist\lib\arborist\build-ideal-tree.js:485:7)
40 verbose stack     at async #applyUserRequests (C:\Program Files\nodejs\node_modules\npm\node_modules\@npmcli\arborist\lib\arborist\build-ideal-tree.js:420:7)
40 verbose stack     at async Arborist.buildIdealTree (C:\Program Files\nodejs\node_modules\npm\node_modules\@npmcli\arborist\lib\arborist\build-ideal-tree.js:195:7)
40 verbose stack     at async Promise.all (index 1)
40 verbose stack     at async Arborist.reify (C:\Program Files\nodejs\node_modules\npm\node_modules\@npmcli\arborist\lib\arborist\reify.js:159:5)
41 verbose cwd Z:\rpa\rpa-image-loader\node_modules\opencv4nodejs-prebuilt
42 verbose Windows_NT 10.0.22621
43 verbose node v20.5.1
44 verbose npm  v9.8.0
45 error code ETARGET
46 error notarget No matching version found for @nut-tree/opencv-build-win32@undefined.
47 error notarget In most cases you or one of your dependencies are requesting
47 error notarget a package version that doesn't exist.
48 verbose exit 1
49 timing npm Completed in 364ms
50 verbose unfinished npm timer reify 1692235644684
51 verbose unfinished npm timer reify:loadTrees 1692235644688
52 verbose unfinished npm timer idealTree:userRequests 1692235644705
53 verbose code 1
54 error A complete log of this run can be found in: C:\Users\AppData\Local\npm-cache\_logs\2023-08-17T01_27_24_367Z-debug-0.log
```

**Comment by s1hofmann** [comment]
Hi @leandjb 👋 

as stated in the readme and the docs, `@nut-tree/template-matcher` is only compatible with node up to version 16

![IMG_7955](https://github.com/nut-tree/TemplateMatcher/assets/7813765/827d2ae3-650c-4764-9ea2-6b97274165fa)

The error message confirms that there is no build for v20:

`No prebuilt binaries found (target=20.5.1 runtime=node arch=x64 libc= platform=win32`
